import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('navigation uses a clean home overlay and distributed top bar', () => {
  const navSource = readFileSync(new URL('../src/components/Nav/Nav.jsx', import.meta.url), 'utf8')
  const navCss = readFileSync(new URL('../src/components/Nav/Nav.css', import.meta.url), 'utf8')

  assert.match(navSource, /const navLinks = siteContent\.nav/)
  assert.match(navSource, /className="nav__grid"/)
  assert.match(navSource, /className="nav__theme-dock"/)
  assert.match(navSource, /TextSwap/)
  assert.match(navSource, /<\/header>\s*\n\s*<div className="nav__theme-dock"/)
  assert.match(navSource, /Dark/)
  assert.match(navSource, /Light/)
  assert.doesNotMatch(navSource, /contactLink/)
  assert.doesNotMatch(navSource, /nav__actions/)
  assert.doesNotMatch(navSource, /nav__cta/)
  assert.doesNotMatch(navSource, /nav__inner--home/)
  assert.doesNotMatch(navSource, /nav__inner--interior/)
  assert.match(navCss, /\.nav__grid/)
  assert.match(navCss, /grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(navCss, /\.nav__theme-dock[\s\S]*position:\s*fixed/)
  // Dock hugs the viewport edge (not --layout-pad) so it never collides with
  // page content, which is inset by --layout-pad on desktop.
  assert.match(navCss, /\.nav__theme-dock[\s\S]*left:\s*0\.9rem/)
  assert.match(navCss, /\.nav__theme-dock[\s\S]*top:\s*50%/)
  assert.match(navCss, /\.nav__theme-dock[\s\S]*transform:\s*translateY\(-50%\)\s*rotate\(-90deg\)/)
  assert.match(navCss, /\.nav__theme-dock[\s\S]*transform-origin:\s*left center/)
  assert.match(navCss, /\.nav__item[\s\S]*justify-self:\s*center/)
  assert.match(navCss, /\.nav__item--link[\s\S]*font-weight:\s*500/)
  assert.match(navCss, /\.nav__item--brand:is\(:hover,\s*:focus-visible\)[\s\S]*letter-spacing:/)
  assert.match(navCss, /\.nav__item--brand:is\(:hover,\s*:focus-visible\)[\s\S]*opacity:/)
  assert.doesNotMatch(navCss, /\.nav__item--brand[\s\S]*justify-self:\s*start/)
  assert.doesNotMatch(navCss, /\.nav__item--link:last-child[\s\S]*justify-self:\s*end/)
  assert.match(navSource, /nav__menu-bar nav__menu-bar--top/)
  assert.match(navSource, /nav__menu-bar nav__menu-bar--middle/)
  assert.match(navSource, /nav__menu-bar nav__menu-bar--bottom/)
  assert.match(navCss, /\.nav__menu-bar/)
  assert.match(navCss, /\.nav__menu--open\s+\.nav__menu-bar--top[\s\S]*rotate\(45deg\)/)
  assert.match(navCss, /\.nav__menu--open\s+\.nav__menu-bar--middle[\s\S]*opacity:\s*0/)
  assert.match(navCss, /\.nav__menu--open\s+\.nav__menu-bar--bottom[\s\S]*rotate\(-45deg\)/)
  assert.match(navSource, /menuOpen \? ' nav--menu-open' : ''/)
  assert.match(navCss, /\.nav--menu-open[\s\S]*z-index:\s*var\(--z-nav-open\)/)
  assert.match(navCss, /\.nav__item:is\(:hover,\s*:focus-visible\)\s+\.text-swap__layer[\s\S]*transition-delay:/)
  assert.doesNotMatch(navCss, /\.nav__inner--home/)
  assert.doesNotMatch(navCss, /\.nav__inner--interior/)
})

test('home nav only uses the light-on-dark treatment while the reel media stage is active', () => {
  const navSource = readFileSync(new URL('../src/components/Nav/Nav.jsx', import.meta.url), 'utf8')
  const navCss = readFileSync(new URL('../src/components/Nav/Nav.css', import.meta.url), 'utf8')

  assert.match(navSource, /home-reel-stagechange/)
  assert.match(navSource, /setHomeOnDarkStage/)
  assert.match(navSource, /detail\.tone/)
  assert.match(navSource, /nav--home-stage/)
  assert.match(navCss, /\.nav--home-stage\s+\.nav__item/)
  assert.doesNotMatch(navCss, /\.nav--home\s+\.nav__item/)
  assert.match(navSource, /scrolled && !isHome/)
  assert.doesNotMatch(navSource, /document\.querySelector\('\.home-end'\)/)
})

test('main layout skips the traditional footer on home', () => {
  const layoutSource = readFileSync(new URL('../src/layouts/MainLayout.jsx', import.meta.url), 'utf8')
  const footerSource = readFileSync(new URL('../src/components/Footer/Footer.jsx', import.meta.url), 'utf8')

  assert.match(layoutSource, /const isHome = location\.pathname === '\/'/)
  assert.match(layoutSource, /className="skip-link"/)
  assert.match(layoutSource, /!\s*isHome\s*&&\s*<Footer \/>/)
  assert.doesNotMatch(footerSource, /footer--minimal/)
  assert.doesNotMatch(footerSource, /if \(isHome\)/)
})

test('mobile navigation exposes stronger dialog accessibility hooks', () => {
  const navSource = readFileSync(new URL('../src/components/Nav/Nav.jsx', import.meta.url), 'utf8')

  assert.match(navSource, /menuButtonRef/)
  assert.match(navSource, /firstFocusable/)
  assert.match(navSource, /lastFocusable/)
  assert.match(navSource, /event\.key === 'Escape'/)
  assert.match(navSource, /aria-labelledby="nav-mobile-title"/)
  assert.match(navSource, /id="nav-mobile-title"/)
  assert.match(navSource, /tabIndex=\{-1\}/)
})

test('theme transition uses a flash veil while keeping the home reel stable', () => {
  const themeSource = readFileSync(new URL('../src/components/ThemeTransition/ThemeTransition.jsx', import.meta.url), 'utf8')
  const themeCss = readFileSync(new URL('../src/components/ThemeTransition/ThemeTransition.css', import.meta.url), 'utf8')
  const reelCss = readFileSync(new URL('../src/components/HomeReel/HomeReel.css', import.meta.url), 'utf8')

  assert.match(themeSource, /theme-veil/)
  assert.match(themeSource, /veilRef/)
  assert.match(themeSource, /opacity/)
  assert.doesNotMatch(themeSource, /theme-orb/)
  assert.doesNotMatch(themeSource, /xPercent/)
  assert.match(themeCss, /\.theme-veil/)
  assert.match(themeCss, /position:\s*fixed/)
  assert.match(themeCss, /display:\s*none/)
  assert.doesNotMatch(themeCss, /\.theme-orb/)
  assert.doesNotMatch(themeCss, /radial-gradient\(circle/)
  assert.doesNotMatch(reelCss, /\.home-reel__title[\s\S]*color:\s*var\(--text\)/)
  assert.doesNotMatch(reelCss, /\.home-reel__view[\s\S]*color:\s*var\(--text\)/)
  assert.doesNotMatch(reelCss, /\.home-reel__band-fill[\s\S]*var\(--text\)/)
})

test('page transition uses a horizontal wipe with content parallax instead of a curtain only', () => {
  const transitionSource = readFileSync(new URL('../src/components/PageTransition/PageTransition.jsx', import.meta.url), 'utf8')
  const transitionCss = readFileSync(new URL('../src/components/PageTransition/PageTransition.css', import.meta.url), 'utf8')

  assert.match(transitionSource, /stageRef/)
  assert.match(transitionSource, /wipeRef/)
  assert.match(transitionSource, /className="page-stage"/)
  assert.match(transitionSource, /className="page-stage__wipe"/)
  assert.match(transitionSource, /xPercent/)
  assert.match(transitionSource, /gsap\.fromTo\(/)
  assert.doesNotMatch(transitionSource, /yPercent/)
  assert.match(transitionCss, /\.page-stage/)
  assert.match(transitionCss, /\.page-stage__wipe/)
  assert.match(transitionCss, /background:\s*var\(--curtain/)
})
